### ISSUE TITLE
РК №2

### ISSUE THREAD

**Issue by vileven** [frontend-park-mail-ru/2019_2_Next_Level#31]
Смотрел по ссылке из README https://nextlevel.now.sh/settings/user-info

- [ ] Есть проблемы с роутингом, обновление страницы не работает :(
![image](https://user-images.githubusercontent.com/22821077/70807313-5ed97700-1dce-11ea-9b9a-0f3c47ce48aa.png)
- [ ] почему то ответные письма не показываются на списке писем :( из-за этого не могу протестить нормально список писем и чтение письма.
- [ ] Нельзя удалить письмо :( Зачем нужна кнопка тогда ... И есть много кнопок, которые ничего не делают
- [ ] Не работает оффлайн

**Comment by tamerlanchik** [comment]
1) проблемы с роутингом - это глючит now, заходит только с корня, на выделенном сервере должно быть нормально.
2) признаю, прием писем постоянно отваливается, но по продуктовым требованиям оно надо только к 4 рк, так что...
3) в этой версии ничего не делают только кнопки удаления письма и смены аватарки. Мы отнесли удаление к статусам, а потому сделали к 3му рк (деплой в процессе)
4) да :( насколько это критично?

**Comment by tamerlanchik** [comment]
1) проблемы с роутингом - это глючит now, заходит только с корня, на выделенном сервере должно быть нормально.
2) признаю, прием писем постоянно отваливается, но по продуктовым требованиям оно надо только к 4 рк, так что...
3) в этой версии ничего не делают только кнопки удаления письма и смены аватарки. Мы отнесли удаление к статусам, а потому сделали к 3му рк (деплой в процессе)
4) да :( насколько это критично?
